import type { Metadata } from "next";
import { Aboreto, Manrope, Poppins, Amiko } from "next/font/google";
import "./globals.css";
import { Footer } from "@/src/components/Hero/Footer";

// Define las fuentes
const aboreto = Aboreto({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-aboreto",
});

const manrope = Manrope({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-manrope",
});

const poppins = Poppins({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-poppins",
});

const amiko = Amiko({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-amiko",
});

// Metadata sin incluir las fuentes
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${aboreto.variable} ${amiko.variable} ${poppins.variable} ${manrope.variable} antialiased overflow-x-hidden `}
      >
        {children}
        <Footer />
      </body>
    </html>
  );
}
